services:
  iSponsorBlockTV:
    image: ghcr.io/dmunozv04/isponsorblocktv:latest
    container_name: iSponsorBlockTV
    restart: unless-stopped

    labels:
      - homepage.group=Media
      - homepage.name=iSponsorBlockTV
      - homepage.id=isponsorblocktv
      - homepage.weight=2
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/youtube.webp
      - homepage.description=Skip YouTube sponsorships

    volumes:
      - ./data:/app/data
    networks:
      - traefik

networks:
  traefik:
    external: true
