---
http:
  services:
    homebridge:
      loadbalancer:
        servers:
          - url: "http://{{env "HOME_IP_ADDRESS"}}:8581"
  routers:
    homebridge:
      entrypoints: websecure
      rule: Host(`homebridge.{{env "DOMAIN"}}`)
      service: homebridge
