---
http:
  services:
    homebridge:
      loadbalancer:
        servers:
          - url: "http://192.168.1.15:8581"
  routers:
    homebridge:
      entrypoints: websecure
      rule: Host(`homebridge.atyaga.duckdns.org`)
      service: homebridge
