services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped

    labels:
      - homepage.group=Containers
      - homepage.name=CAdvisor
      - homepage.id=cadvisor
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/cadvisor.webp
      - homepage.showStats=true

    volumes:
      - /:/rootfs:ro,rslave
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
      - /dev/disk/:/dev/disk:ro,rslave
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - traefik

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped

    labels:
      - homepage.group=Containers
      - homepage.name=Node Exporter
      - homepage.id=node_exporter
      - homepage.showStats=true
      - homepage.icon=mdi-swap-vertical

    command:
      - --path.rootfs=/host
    pid: host
    volumes:
      - /:/host:ro,rslave
    networks:
      - traefik  

  vmagent:
    image: victoriametrics/vmagent:latest
    container_name: vmagent
    restart: unless-stopped

    labels:
      - homepage.group=Containers
      - homepage.name=VM Agent
      - homepage.id=vmagent
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/vercel.webp
      - homepage.showStats=true

    environment:
      - HOME_IP_ADDRESS=$HOME_IP_ADDRESS
      - DOMAIN=$DOMAIN

    depends_on:
      - victoriametrics
      - cadvisor
      - node_exporter
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - vmagent-data:/vmagentdata
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    networks:
      - traefik

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    restart: unless-stopped
    labels:
      - homepage.group=Containers
      - homepage.name=VictoriaMetrics
      - homepage.id=victoriametrics
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/victoriametrics.webp
      - homepage.showStats=true

    volumes:
      - victoriametrics_data:/storage
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
      - "--retentionPeriod=100y"
      - "--selfScrapeInterval=60s"
      - "--maxLabelsPerTimeseries=200"
    networks:
      - traefik

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped

    labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)
      - traefik.http.routers.grafana.entrypoints=websecure

    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - DS_PROMETHEUS=prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./dashboards/:/var/lib/grafana/dashboards/
      - ./default.yaml:/etc/grafana/provisioning/dashboards/default.yaml
    privileged: true
    depends_on:
      - victoriametrics
    networks:
      - traefik  

networks:
  traefik:
    external: true

volumes:
  grafana-data:
  vmagent-data:
  victoriametrics_data:

# https://grafana.com/grafana/dashboards/1860-node-exporter-full/
# https://grafana.com/grafana/dashboards/893-main/

