global:
  scrape_interval: 15s
#  evaluation_interval: 15s
  
scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: 
      - victoriametrics:8428

  - job_name: cadvisor
    static_configs:
    - targets: 
      - cadvisor:8080

  - job_name: node_exporter
    static_configs:
    - targets: 
      - node_exporter:9100

  - job_name: homebridge-exporter
    static_configs:
    - targets:
      - %{HOME_IP_ADDRESS}:36123

  - job_name: watchtower
    scrape_interval: 30m
    metrics_path: /v1/metrics
    bearer_token: watchtower_token
    static_configs:
      - targets:
        - %{HOME_IP_ADDRESS}:8090

  - job_name: traefik
    static_configs:
      - targets: 
        - %{HOME_IP_ADDRESS}:8899

  - job_name: myspeed
    metrics_path: /api/prometheus/metrics
    static_configs:
      - targets:
          - %{HOME_IP_ADDRESS}:5216
