---

api:
  dashboard: true
  debug: true
  disabledashboardad: true

log:
  level: INFO

accesslog: false

metrics:
  addInternals: true
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    watch: true
  file:
    directory: /etc/traefik/dynamic
    watch: true

entrypoints: 
  metrics:
    address: ":8899"
  websecure:
    address: ":443"
    asDefault: true
    http:
      tls:
        certresolver: cloudflare
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https

certificatesresolvers:
  cloudflare:
    acme:
      email: "<atyaga@gmail.com>"
      storage: /letsencrypt/acme_cf.json
      dnschallenge:
        provider: cloudflare
        resolvers: 1.1.1.1:53,1.0.0.1:53
