services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped

    labels:
      - traefik.enable=true
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - traefik.http.routers.homepage.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.homepage.entrypoints=websecure

      - homepage.group=Applications
      - homepage.name=Homepage
      - homepage.id=homepage
      - homepage.weight=1
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/homepage.webp
      - homepage.href=https://$DOMAIN/
      - homepage.siteMonitor=https://$DOMAIN/
      - homepage.ping=$DOMAIN
      - homepage.target=_self
      - homepage.description=Tyaga's Dashboard
    environment:
      - LOG_TARGETS=stdout
      - HOMEPAGE_VAR_DOMAIN=$DOMAIN

    user: 1000:1000
    group_add: ['971'] # docker

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/config

    networks:
      - traefik

networks:
  traefik:
    external: true
