# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

---
- Bookmarks:
    - Gmail:
        - href: https://mail.google.com/mail/u/0/#inbox
          icon: gmail.png
    - Physical:
        - href: https://content.pht.space/#/flow-program
          icon: https://content.pht.space/static/favicon.png
    - YouTube:
        - href: https://youtube.com/
          icon: youtube.png
    - Bunq:
        - href: https://web.bunq.com/user/7834557
          icon: https://web.bunq.com/assets/favicon-BjGKPVkG.ico

- ITT Bookmarks:
    - Gitlab:
        - abbr: GL
          href: https://gitlab.corp.my.games/

