---
# https://gethomepage.dev/configs/info-widgets/

- logo:

- glances:
    url: https://glances.{{HOMEPAGE_VAR_DOMAIN}}
    version: 4
    cpu: true
    mem: true
    cputemp: true
    uptime: true
    disk: true
    expanded: false

- resources:
    expanded: false
    disk:
        - /

- openmeteo:
    label: Haarlem
    latitude: 53.709807
    longitude: 27.953389
    units: metric
    provider: openmeteo
    cache: 10
    format:
        maximumFractionDigits: 1

- datetime:
    text_size: 3xl
    format:
        timeStyle: medium

