services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped

    labels:
      - traefik.enable=true
      - traefik.http.services.dockge.loadbalancer.server.port=5001
      - traefik.http.routers.dockge.rule=Host(`dockge.${DOMAIN}`)
      - traefik.http.routers.dockge.entrypoints=websecure

      - homepage.group=Setup
      - homepage.weight=5
      - homepage.name=Dockge
      - homepage.id=dockge
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/dockge.webp
      - homepage.href=https://dockge.$DOMAIN/
      - homepage.description=Running docker containers

    user: 1000:1000
    group_add: ['971'] # docker

    environment:
      - DOCKGE_STACKS_DIR=$ABSOLUTE_PATH/stacks

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $ABSOLUTE_PATH/data/dockge:/app/data
      - $ABSOLUTE_PATH/stacks:$ABSOLUTE_PATH/stacks

    networks:
      - traefik

networks:
  traefik:
    external: true

